apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-slack-app-secret
  namespace: ${namespace}
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ${secret_store_ref_name}
    kind: ClusterSecretStore
  target:
    name: ${argocd_slack_app_secret}
  dataFrom:
  - extract:
      key: ${awssm_secret_name}