apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: ${role_name}
  detailedMonitoring: true
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${cluster_name}/public
  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/${cluster_name}: owned
  userData: |
    echo "Hello world"
  tags:
    karpenter.sh/discovery: ${cluster_name}
    Name: from-karpenter
