apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slack-test-notification
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:kwatatshey/labs-terraform.git
    path: templates/aws/charts/engines/argocd/slack/slack_poc/manifests 
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
