apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${producer_deployment_name}
  namespace: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${producer_deployment_name}
  template:
    metadata:
      labels:
        app: ${producer_deployment_name}
    spec:
      serviceAccountName: ${py_service_account_name}
      containers:
      - name: ${producer_deployment_name}
        image: asyncdeveloper/keda-py-test
        imagePullPolicy: Always
        env:
        - name: SQS_QUEUE_URL
          value: ${sqs_queue_url}
        - name: SQS_QUEUE_NAME
          value: ${sqs_queue_name}
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            memory: 128Mi
            cpu: 500m