apiVersion: v1
kind: Service
metadata:
  name: canary-service-demo
  namespace: ${namespace}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: ${app_selector_label}