  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: app-of-apps
    namespace: ${namespace}
  spec:
    project: ${app_proj}
    source:
      repoURL: ${ssh_clone_url}
      path: ${path}
      targetRevision: HEAD
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: ${namespace}
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true