apiVersion: batch/v1
kind: Job
metadata:
  name: degraded-job
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
        - >
          exit 1;
      restartPolicy: Never
  backoffLimit: 1