apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: global-cluster-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${region}
      auth:
        jwt:
          serviceAccountRef:
            name: ${serviceaccount}
            namespace: ${namespace}